name: SSHX Runner

on:
  workflow_dispatch:

jobs:
  sshx:
    runs-on: codespaces-prebuild

    steps:
      - name: Install sshx
        run: |
          curl -sSf https://sshx.io/get | sh -s run

      - name: Keep runner alive
        run: |
          tail -f /dev/null
